### ISSUE TITLE
Corrigir método assemble quando há uma única entrada que usa diretivas de módulos

### ISSUE THREAD

**Issue by adornelas** [adornelas/AssemblerLinker#10]
Quando o programa é executado com apenas um arquivo como parâmetro e este arquivo é um módulo, o programa dá seg fault.

Mais especificamente na função TranslateAssemblyToObject, quando encontra uma diretiva diferente de CONST e SPACE, na hora em que a linha 

opcode = stol(op_code_map.find(matrix_line[j])->second);

é chamada, o método .find não encontra a diretiva BEGIN, por exemplo, e dá um seg fault.

**Comment by MariaClaudia1328** [comment]
corrigi na branch #23
