### ISSUE TITLE
Implementar identificação de erros

### ISSUE THREAD

**Issue by MariaClaudia1328** [adornelas/AssemblerLinker#4]
## Descrição

Identificar os seguintes erros:
   - [x] Dois rotulos na mesma linha
   - [x] Rótulo não definido na seção de TEXT
   - [x] Dado não definido na seção DATA
   - [x] Seção TEXT faltante
   - [x] EXTERN e PUBLIC em arquivo que NAO tenha BEGIN e END
   - [x] Erros Iéxicos (caracteres especiais fora o “_” (underscore) ou “numero inicial nos
    rótulos)

Além disso, vale notar que mesmo existindo os erros, o arquivo exc deve ser criado. 

Outro ponto importante é que deve informar se o erro é lexico, sintatico ou semantico.

Dado como o montador foi feito, podemos identificar os erros no arquivo pre processado e indicar em qual linha o erro aconteceu. Mas isso deve ser avisado no README.md.

**Comment by adornelas** [comment]
Também é necessário informar a linha do onde o erro está

**Comment by MariaClaudia1328** [comment]
> Também é necessário informar a linha onde o erro está

Beleza anotei certinho na descrição

**Comment by MariaClaudia1328** [comment]
No algoritmo do montador, alguns erros foram adicionados. São eles 

- Rótulo duplicado
- Simbolo que não foi definido 

Considerei eles como erros semânticos e defini um padrão de mensagem para todos os erros como 

```
<tipo_do_erro> : <descrição> (linha %d)
```

**Comment by MariaClaudia1328** [comment]
Sobre o erro de CONST não aceitar números negativos em hexadecimal, preciso levar essa identificação pra depois do pre-processamento. O mesmo vai acontecer caso o numero seja ponto flutuante
